name: run the workflow

on:
  repository_dispatch:
    types: [my-event]
    
jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven 
      - name: Simple Test Run
        run:     
          mvn clean test
          