name: workflow01

on:
  push:
    branches:
      - main
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Simple Test Run
        run:     
          mvn clean test
          
  trigger-workflow02:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow02
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: Akshit-shiv/AkshitHomeTest
          event-type: trigger-workflow02