name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "This workflow has been triggered!"
