name: Trigger integration with Test Dev

on: [push]
  
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Repository Name
        run: echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - name: Display Repository Name
        run: echo $REPOSITORY_NAME
      - name: workspace name
        run:
          echo $GITHUB_REPOSITORY
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Simple Test Run
        run:     
          mvn clean test