name: Trigger integration with Test Dev

on:
  workflow-call:
  
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: workspace name
        run:
          echo $GITHUB_REPOSITORY
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Simple Test Run
        run:     
          mvn clean test