name: Trigger test in another repo checks

on: 
  push:
    branches:
      - main

jobs:
  calledWorkflow:
    uses: Akshit-shiv/AkshitHomeTest/.github/workflows/sample.yml@main
    with:
      token: ${{secrets.TEST_REPO_TOKEN}}
