name: run the workflow

on:
  repository_dispatch:
    types: [my-event]
    
jobs:
  run-workflow:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Run Simple Test
        run: mvn clean test
    