name: run the workflow

on:
  workflow_call:
 
jobs:
  run-workflow:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: Akshit-shiv/AkshitHomeTest
          ref: main # or specify the branch you want to checkout
          token: ${{ secrets.TEST_REPO_TOKEN }} # Replace with a GitHub token with repository access to the target repository
        
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # or any other version you require
          distribution: 'temurin'
      - name: Run Maven Tests
        run: mvn clean test
    