name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "This workflow has been triggered again!"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Simple Test Run
        run:     
          mvn clean test